---
title: "git_00"
author: "Your Name here"
date: "Year 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
And cannot pleasures, while they last,
  
Be actual unless, when past,
  
They leave us shuddering and aghast,
  
With anguish smarting?
  
And cannot friends be firm and fast,
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
From blade of grass to the tip of twig,
  
The white dust of winter fall’s.
  
Frenzied  flakes move in lost abandonment,
  
Finally pitch on fence and wall’s.
  
On the throat the rasping of cold crisp air,
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
"The sun was shining on the sea,
  
Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
  
I love your lips when they’re wet with wine
  
  
And red with a wild desire; 
  
I love your eyes when the lovelight lies 
  
Lit with a passionate fire. 
  
I love your arms when the warm white flesh 
  
Touches mine in a fond embrace; 
  
I love your hair when the strands enmesh 
  
Your kisses against my face. 